audit_header: false
title: -- MARKET -- Real Estate Video Blog with -- CLIENT NAME --
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Schedule a Meeting with Me
    url: https://calendly.com/robertmack
show_custom_links_new_tab: true
custom_links_new_tab:
  - title: Testimonials
    url: /testimonials/

client:
  name: Robert Mack
  title:
  license_number: CA BRE# 01734565
  about_markdown: |
    All of our clients come with a real story and no two clients we work with are ever alike.  Everyone is unique and that’s what makes real estate so interesting and exciting at the Robert Mack Group.  There isn’t a one size fits all approach, and it truly takes a talented group of individuals working together as a team to create structure in an industry full of chaos, emotion, excitement, and fear!

    Maybe you’re a terrified first time home buyer and scraping together everything you have just to own your own home?  You could be a family of 3 or 4 running out of the room, and it’s time to upgrade to a bigger home?  Maybe you tried to sell once and weren’t able to and now you need a new approach.  Have your kids all grown up and moved out, and you are sick of taking care of such a big home and it’s time to get a smaller place?  Maybe you just got married, or are going through a divorce?  Life is unpredictable sometimes. There are so many stories and we’ve heard and seen almost everything but every now and then we get approached by a client with a scenario we’ve never come across….and that’s where we shine!

    Real estate is more than just opening doors or showing homes.  It’s not just about putting a sign out front of your home and putting it online.  It’s about people.  People who need help to buy or sell a home for one reason or another.

    My wife, Tania, and I are team leaders at the Robert Mack Group @ Keller Williams International.  Our team consists of 6 individuals that work together to make sure every client we work with has an unparalleled customer experience from the moment we meet.

    If you are looking to sell your current home, buy a new home, or both, we'd like to learn more.  There is never any cost or obligation to meet with us for a private consultation, to determine if we are the right fit for you.

    To get a better feel for who we are and how we can help, please take a moment to read a few of our past client reviews.
  brand: Robert Mack Group
  brokerage: Keller Williams Realty
  market:
  address: 4010 Barranca Park Way, Suite 100 Irvine, CA 92604
  phone: 949-209-7309
  phone_type:
  phone2:
  phone2_type:
  email: robertm@robertmackgroup.com
  url: http://www.irvinerealestatelink.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.searchforhomesinoc.com/homevalue/Irvine
  second_CTA_text: Home Search
  second_CTA_URL: https://www.searchforhomesinoc.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.searchforhomesinoc.com/homevalue/Irvine

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.searchforhomesinoc.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 30
  hero_text: 
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#9D9185'
  theme_color: '#000000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
